language: node_js
  - 12.18.0
node_js:
  - 'stable'
addons:
  apt:
    packages:
      - libgconf-2-4
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
cache:
  npm: true
  directories:
    - 'node_modules'
    - ~/.cache
install:
  - npm ci
script:
  - npm run check
  - npm run game:build:prod
  - npm run loki:ci
  - npm run cy:verify
  - npm run cy:ci
